### ISSUE TITLE
`readFile` on directory should throw meaningful errors

### ISSUE THREAD

**Issue by zardoy** [zen-fs/dom#11]
I tested reading file with WebAccess backend which was actually a directory and it gave me the following error:

(in promise) TypeError: Cannot read properties of undefined (reading 'close')
    at _readFile (promises.js:471:20)

For example, calling readdir on a file gives the following error: `ENOTDIR: File is not a directory`

**Comment by dr-vortex** [comment]
@zardoy [v0.2.5](https://github.com/zen-fs/dom/releases/tag/v0.2.5) should fix the issue.

**Comment by zardoy** [comment]
hhey sorry i didnt update yet to check it. in fact since everything is the same in terms of performance as in browserfs I'm not sure if I'm updating
