### ISSUE TITLE
WebAccess to OPFS throws TypeError  on write

### ISSUE THREAD

**Issue by atty303** [zen-fs/dom#12]
The errors are as follows

> Failed to execute 'write' on 'FileSystemWritableFileStream': The provided ArrayBufferView value must not be resizable.

This is where the resizable ArrayBufferView comes from.

https://github.com/zen-fs/core/blob/main/src/file.ts#L558
```ts
const newBuffer = new Uint8Array(new ArrayBuffer(endFp, { maxByteLength: size_max }));
```

I think there should be a flag in the constructor of PreloadFile to indicate whether resizable buffers should be used.
Or maybe the only way to do writeFile with WebAccessFS is to copy the buffer?

**Comment by dr-vortex** [comment]
I think this is a good use for `FileSystem.metadata`.

**Comment by dr-vortex** [comment]
Sorry for the repeated "added a commit to zen-fs/core that referenced this issue", I messed up the commit message =[

**Comment by dr-vortex** [comment]
@atty303 Does [0.2.10](https://github.com/zen-fs/dom/releases/tag/v0.2.10) fix the issue?

**Comment by atty303** [comment]
I will wait for ZipFS to update this one as well. (https://github.com/zen-fs/core/issues/64)

**Comment by dr-vortex** [comment]
As I mentioned in [zen-fs/core#64](https://github.com/zen-fs/core/issues/64), I had not released the Zip updates yet. [@zenfs/zip v0.4.0](https://github.com/zen-fs/zip/releases/tag/v0.4.0) should be up to date.

**Comment by atty303** [comment]
I can confirm that this problem has been fixed.
