### ISSUE TITLE
configuration using IndexedDB not working

### ISSUE THREAD

**Issue by mrtechtroid** [zen-fs/dom#14]
Using IndexedDB in configuration, results in error `Error: Function not implementedat _ErrnoError.With`. Using the code:
```ts
await configure({
	mounts: {
		// '/local': { backend: WebStorage, storage: localStorage },
		'/tmp': InMemory,
		'/home': {backend: WebStorage, storage: localStorage },
		'/indexdb': IndexedDB
	}
});
```
Any fix/suggestion would be greatly helpful!

**Comment by dr-vortex** [comment]
@mrtechtroid,

Thanks for submitting an issue. Could you please provide a full stack trace? Also, providing the error's `syscall` property will help a lot.

**Comment by Fr0stbyteR** [comment]
same error here, seems that zenfs attempts to make IndexedDB backend synchronized.

**Comment by Fr0stbyteR** [comment]
```
Uncaught Error: Function not implemented
    at ErrnoError.With (error.js:249:1)
    at IndexedDBTransaction.getSync (store.js:48:25)
    at StoreFS.makeRootDirectorySync (fs.js:402:1)
    at new StoreFS (fs.js:40:1)
    at Object.create (IndexedDB.js:112:1)
    at async resolveMountConfig (config.js:43:1)
    at async Module.configure (config.js:72:1)
```

**Comment by dr-vortex** [comment]
This is because `AsyncTransaction` does not support caching. This is fixed by [core 6c9dd2b](https://github.com/zen-fs/core/commit/6c9dd2b13891d0bc8a852542bcca72789840f6de). However, I would like to make sure it works with the `disableAsyncCache` option prior to releasing it.

**Comment by mrtechtroid** [comment]
Hi there! does this mean all of the `fs.<function>` would work as intended for IndexedDB based storage once this is released? (Similar to its working with localStorage)

**Comment by mrtechtroid** [comment]
Hi there, No I still seem to be unable to use IndexedDB. The error has been mentioned below. 
```
Uncaught (in promise) Error: Function not implemented
    at _ErrnoError.With (chunk-5SOV2WSV.js?v=5e1327bf:8474:12)
    at IndexedDBTransaction.getSync (chunk-5SOV2WSV.js?v=5e1327bf:10777:22)
    at _AsyncFS.makeRootDirectorySync (chunk-5SOV2WSV.js?v=5e1327bf:10434:12)
    at new StoreFS (chunk-5SOV2WSV.js?v=5e1327bf:10121:12)
    at new _AsyncFS (chunk-5SOV2WSV.js?v=5e1327bf:9747:7)
    at Object.create (@zenfs_dom.js?v=5e1327bf:367:16)
    at async resolveMountConfig (chunk-5SOV2WSV.js?v=5e1327bf:13938:18)
    at async configure (chunk-5SOV2WSV.js?v=5e1327bf:13962:28)
```

**Comment by dr-vortex** [comment]
Ah, this makes sense because `_disableSync` is not set until after the constructor runs, and the constructor called `makeRootDirectorySync`, which caused the error. [core v0.12.9](https://github.com/zen-fs/core/releases/tag/v0.12.9) should fix it. Please let me know.

**Comment by mrtechtroid** [comment]
Unfortunately it gives a different error now. 
```
Uncaught (in promise) Error: No sync cache is attached to this async file system
    at _AsyncFS.checkSync (chunk-O22TGT6O.js?v=cf228c7f:9780:15)
    at _AsyncFS.ready (chunk-O22TGT6O.js?v=cf228c7f:9765:12)
    at async resolveMountConfig (chunk-O22TGT6O.js?v=cf228c7f:13940:3)
    at async configure (chunk-O22TGT6O.js?v=cf228c7f:13960:28)
```

**Comment by dr-vortex** [comment]
@mrtechtroid,

Sorry for taking so long to get back to you. I was preoccupied with some important events.

I attempted to fix this in [core#1e148be](https://github.com/zen-fs/core/commit/1e148be7e23c4015449019f209068934a8eb8757), but that leads to a circular dependency and is not viable. 

Please let me know if [0.2.13](https://github.com/zen-fs/dom/releases/tag/v0.2.13) fixes the issue. Note that you will need core v0.12.10+

**Comment by mrtechtroid** [comment]
Unfortunately it gives the same error as above even after updating. `No sync cache is attached to this async file system`.

**Comment by dr-vortex** [comment]
Can you check the value of `_sync`?

```ts
const idbfs = await resolveMountConfig({
    backend: IndexedDB,
    // ...
});

console.log(idbfs._sync);
```

**Comment by mrtechtroid** [comment]
Hi there, `resolveMountConfig` itself gives an error. (The value of `this._sync` in the debugger is set to `undefined`)

**Comment by dr-vortex** [comment]
Sorry for taking so long to get back to you, I've been very busy. On to the issue:

[src/IndexedDB.ts:152](https://github.com/zen-fs/dom/blob/cde51d733a2ab41ac63bf5f26805d132ce202f78/src/IndexedDB.ts#L152) should set `_sync` to a `InMemory` instance. Could you please check the value after that line? I've tested it locally and it works correctly.

**Comment by mrtechtroid** [comment]
It is being set as `const fs = new (Async(StoreFS))(store);` which may have been cause of the issue.

**Comment by dr-vortex** [comment]
This seems to be a likely cause. Please use `IndexedDB.create` if you would like to create a new instance of the backend. I strongly recommend you use `configure` unless you absolutely need to use the backend instance.

**Comment by mrtechtroid** [comment]
@dr-vortex I meant inside my `IndexedDB.create` function (as per npm module) the code is `const fs = new (Async(StoreFS))(store)`. However when i looked at the source code of the repo you gave it is set to a `InMemory`. Is there a newer version than 0.2.12?

**Comment by dr-vortex** [comment]
Yes 0.2.13 has the fix.

**Comment by mrtechtroid** [comment]
Hi, when would 0.2.13 be released?

**Comment by dr-vortex** [comment]
@mrtechtroid 

[v0.2.13](https://github.com/zen-fs/dom/releases/tag/v0.2.13) was released approximately 2 weeks ago.

**Comment by mrtechtroid** [comment]
Hi there, according to npm the latest version is v0.2.12 published 19 days ago. Could you please recheck.

**Comment by dr-vortex** [comment]
@mrtechtroid,

It appears the release failed: https://github.com/zen-fs/dom/actions/runs/9351898468/job/25738843005. I will work on fixing the issue.

**Comment by mrtechtroid** [comment]
Thanks, it works now! Just noticed it takes a very long time for indexedDB to setup itself. Any suggestions to make it faster?

**Comment by dr-vortex** [comment]
@mrtechtroid, I'm glad it works for you know! You can disable the async cache, though you will not be able to use an sync functions then.

**Comment by mrtechtroid** [comment]
Umm could you guide upon how to disable the async cache?

**Comment by mrtechtroid** [comment]
Is it standard for idb to take ~30 seconds to configure itself? (Even when its empty?)
```
                                let t = Date.now()
				const idb_ = await resolveMountConfig({ backend: IndexedDB });
				fs.mount('/drive', idb_);
				$storeFE.iDBloaded = true
				console.log("done! iDB. took time: " + String(Date.now()- t)+"ms")
```
Output: `done! iDB. took time: 29932ms`

**Comment by james-pre** [comment]
30 seconds seems to be quite a lot. Perhaps you could log times at different places to see where the bottleneck is? I suspect `crossCopy` may be responsible but I am unable to replicate the times you are experiencing.

**Comment by mrtechtroid** [comment]
Could you please suggest any methods of mitigating the time taken?

**Comment by james-pre** [comment]
@mrtechtroid,

Sorry about the delayed response. You can find examples in the [port backend readme](https://github.com/zen-fs/core/blob/521e1ab88437120591f05cce4719e0bef3acf4b3/src/backends/port/readme.md)

**Comment by james-pre** [comment]
@mrtechtroid Can I close this issue, or do you still need help?
