### ISSUE TITLE
Issue with idbFactory Setup

### ISSUE THREAD

**Issue by terryluan12** [zen-fs/dom#16]
Within `IndexedDB.ts:isAvailable`, there is a try catch statement, which defaults to `globalThis.indexedDB`. Within the typecheck (line 134), `globalThis.indexedDB` eventually becomes available, but initially, when attempting to access it, it returns an error because `idbFactory` is `undefined`. However because it's undefined when attempting to delete database in the catch statement, it returns an error.

**Comment by terryluan12** [comment]
It actually seems that the code errors because IDBFactory is not defined within Node. Attempting to find a fix for that. Irregardless, the error still occurs because `globalThis.indexedDB` is not defined initially

**Comment by james-pre** [comment]
@terryluan12 This is intentional behavior. As you undoubtedly know, Node is not a browser so browser APIs are not available. You should not use `@zenfs/dom` outside of a browser environment, since it depends on DOM/browser APIs for everything. Does that clear things up?

**Comment by terryluan12** [comment]
Ahhhh. I see, it does! I do see it running fine browser-side, but I think the server side is also running the code (I'm using NextJS). Thank you
