### ISSUE TITLE
XML backend: Store Filesystem inside the DOM

### ISSUE THREAD

**Issue by james-pre** [zen-fs/dom#8]
> Imagine if we have something similar [to] `Storage` but instead of storing it on Local Storage we would store the filesystem inside the DOM.
This would make it possible for a "quine", that is, a program that produces itself as output.
>
> This way we would be able to save the .html file with ctrl+s since the filesystem is inside the DOM and not in the browser(the .html file has the filesystem).
>
> I can do a Pull Request but is this project still going on? Is there an active fork of it?  

~ @ilse-langnar

https://github.com/jvilk/BrowserFS/issues/331

**Comment by james-pre** [comment]
Finally implemented in [1.1.0](https://github.com/zen-fs/dom/releases/tag/v1.1.0). @ilse-langnar I know it has been a couple of *years*, but it is here.

**Comment by ilse-langnar** [comment]
THANKS!!!!!!!
