### ISSUE TITLE
In the `browser.min.js` version, an error occurs.

### ISSUE THREAD

**Issue by Davilarek** [zen-fs/dom#9]
Using this for init.
```js
window.ZenFS.configure({
      backend: window.ZenFS_DOM.IndexedDB,
      storeName: "VirtualFS",
  }).then(() => console.log(window.ZenFS));
```
Getting this error:
```
Uncaught (in promise) TypeError: (destructured parameter) is undefined
    _initialize AsyncStore.ts:162
    ready filesystem.ts:341
    ready AsyncStore.ts:141
    xs config.ts:61
    Pg config.ts:96
    run test.js:9
    async* test.js:14
AsyncStore.ts:162:29
```
From my investigation, `_initialize` seems to run twice and on the second run, it fails.

**Comment by dr-vortex** [comment]
@Davilarek,

I noticed this issue as well and corrected it (though it took me a [few tries](https://github.com/zen-fs/core/compare/v0.7.3..v0.7.8)).

I apologize for not responding to you sooner, I did not have the correct notification settings for this repository.
